name: Basic deploy
on:
  push:
    branches: [main]

jobs:
  Deploy-static-site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          cd ./packages/order
          npm run build
          cd ../../
          tree . -I node_modules|.nx

      - name: Create deploy-bucket
        uses: bitovi/github-actions-deploy-static-site-to-aws@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          aws_site_source_folder: ./packages/order/dist

          tf_action: "apply"
          tf_state_bucket_destroy: true # If destroying, will remove the bucket

          aws_site_cdn_enabled: true

          aws_r53_domain_name: bitovi-sandbox.com # You should own and have this domain available in R53
          aws_r53_sub_domain_name: order-mfe
          aws_r53_create_sub_cert: true # Will create and validate a cert for this sub-domain

          aws_site_bucket_name: order-mfe
